### PR TITLE
Helm and oauth

### PR DESCRIPTION
**Pull request by mrManner**
This PR includes three major changes, that are more or less related:

1. **Replace homemade Kubernetes manifest templates with Helm charts.**
2. **Introduce a staging environment for the wiki.** The deployment pipeline is currently set up to deploy the new Helm charts to staging, wait for confirmation, and then deploy the same things to production. The staging env. is available at wiki.21.jamboree.se.staging.webservices.scouterna.net (controlled in `charts/wiki/values/staging.yaml`).
3. **Replace SAML authentication with Oauth2.** This means we use the same auth method for the wiki and Facelist, with a smoother end user experience. The user now only needs to log in once to either service and select to stay logged in, and can then forget their password (please don't). 

Let's merge and be very careful before approving the deploy through from staging to production. We will need to do some manual steps before the production deploy will work, basically adding an annotation and a label to each wiki-related resource in order to tell Helm that it's fine to update the existing resources. But we'll deal with that when we see the error messages.

Note for the future: The oauth authentication uses a plugin in Kong ingress called external-oauth, somewhat patched by us. It will be documented at some point, until then: It should be enough to add an annotation like `plugins.konghq.com: office-oauth` to the Ingress, and the upstream service will get the end user email in a header `X-Http-Oauth2-Email` and first + last name in `X-Http-Oauth2-Name`.

### CODE REVIEW

**Comment by puggan** [comment]
Den länken jag testade funkade bra, men har inte behörighet att lägga reviews här :-)

**Comment by mrManner** [comment]
> Den länken jag testade funkade bra, men har inte behörighet att lägga reviews här :-)

Haha det kan vi fixa, jag ger dig skrivaccess här också. Just den här vill jag ha Emils ögon på, dock :)

**Comment by mrManner** [comment]
Speaking of testa, jag gjorde en extra pre-release-miljö och deployade den här ändringen där: https://wiki.21.jamboree.se.develop.webservices.scouterna.net/

Parsoid saknas där pga knöligt att deploya, så det är ingen vits med att testa redigering o.s.v men inloggningen ska funka :)

**Comment by mrManner** [comment]
@puggan Du borde visst ha behörighet, du är med i Jamboree21-teamet på Github och det har skrivbehörighet här :S

**Review by zentabit — APPROVED** [review]

**Pull request merged**
